language: cpp
os:
  - linux
compiler:
  - g++
install:
  - sudo pip install codecov
script:
  - make -C make
  - make -C make test
  - make -C make gcov
branches:
  only:
    - master
after_success:
  - codecov -X gcov
