language: cpp
compiler:
- g++
os:
- linux
script:
- make -C make
- make -C make test
- make -C make gcov
branches:
  only:
  - master
after_success:
  - codecov -t c2a3dea6-6a00-425d-a748-095e1a3f5078 -X gcov
